# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldappool',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='ldapserver',
            name='connection',
        ),
        migrations.AddField(
            model_name='ldapconnection',
            name='pool',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='ldap3_sync.LDAPPool'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldappool',
            name='servers',
            field=models.ManyToManyField(related_name='pools', to='ldap3_sync.LDAPServer'),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'wholly.direct.kodiak', max_length=255, unique=True),
        ),
    ]
