# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0002_auto_20170214_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapconnection',
            old_name='sasl_credential',
            new_name='sasl_credentials',
        ),
        migrations.RemoveField(
            model_name='ldapreferralhost',
            name='server',
        ),
        migrations.AddField(
            model_name='ldapconnection',
            name='auto_range',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='allowed_referral_hosts',
            field=models.ManyToManyField(to='ldap3_sync.LDAPReferralHost'),
        ),
        migrations.AddField(
            model_name='ldapserver',
            name='tls',
            field=models.CharField(blank=True, help_text=b'Path to a python object which contains TLS certificate information. LEAVE THIS BLANK.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='auto_bind',
            field=models.CharField(choices=[(b'NONE', b'ldap3.AUTO_BIND_NONE'), (b'NO_TLS', b'ldap3.AUTO_BIND_NO_TLS'), (b'TLS_AFTER_BIND', b'ldap3.AUTO_BIND_TLS_AFTER_BIND'), (b'TLS_BEFORE_BIND', b'ldap3.AUTO_BIND_TLS_BEFORE_BIND')], default=b'NONE', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='client_strategy',
            field=models.CharField(choices=[(b'SYNC', b'ldap3.SYNC'), (b'RESTARTABLE', b'ldap3.RESTARTABLE')], default=b'SYNC', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='sasl_mechanism',
            field=models.CharField(blank=True, choices=[(b'EXTERNAL', b'ldap3.EXTERNAL'), (b'DIGEST-MD5', b'ldap3.DIGEST_MD5'), (b'GSSAPI', b'ldap3.KERBEROS'), (b'GSSAPI', b'ldap3.GSSAPI')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ldappool',
            name='pool_strategy',
            field=models.CharField(choices=[(b'FIRST', b'ldap3.FIRST'), (b'ROUND_ROBIN', b'ldap3.ROUND_ROBIN'), (b'RANDOM', b'ldap3.RANDOM')], default=b'ROUND_ROBIN', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='get_info',
            field=models.CharField(choices=[(b'NO_INFO', b'ldap3.NONE'), (b'DSA', b'ldap3.DSA'), (b'SCHEMA', b'ldap3.SCHEMA'), (b'ALL', b'ldap3.ALL'), (b'EDIR_8_8_8', b'ldap3.OFFLINE_EDIR_8_8_8'), (b'AD_2012_R2', b'ldap3.OFFLINE_AD_2012_R2'), (b'SLAPD_2_4', b'ldap3.OFFLINE_SLAPD_2_4'), (b'DS389_1_3_3', b'ldap3.OFFLINE_DS389_1_3_3')], default=b'SCHEMA', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='mode',
            field=models.CharField(choices=[(b'IP_SYSTEM_DEFAULT', b'ldap3.IP_SYSTEM_DEFAULT'), (b'IP_V4_ONLY', b'ldap3.IP_V4_ONLY'), (b'IP_V6_ONLY', b'ldap3.IP_V6_ONLY'), (b'IP_V4_PREFERRED', b'ldap3.IP_V4_PREFERRED'), (b'IP_V6_PREFERRED', b'ldap3.IP_V6_PREFERRED')], default=b'IP_SYSTEM_DEFAULT', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'freely.hardy.mammal', max_length=255, unique=True),
        ),
    ]
