# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0003_auto_20170214_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapconnection',
            name='sasl_credentials',
            field=models.CharField(blank=True, help_text=b'Path to an object to use as the SASL Credential.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='allowed_referral_hosts',
            field=models.ManyToManyField(blank=True, to='ldap3_sync.LDAPReferralHost'),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'namely.epic.fly', max_length=255, unique=True),
        ),
    ]
