# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0004_auto_20170214_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPSyncAttributeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_attribute_name', models.CharField(help_text=b'LDAP Attribute Name.', max_length=255)),
                ('model_attribute_name', models.CharField(help_text=b'Django Attribute Name.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPSyncDjangoQuerysetFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(help_text=b'Filter predicate.', max_length=255)),
                ('value', models.CharField(help_text=b'Value to filter against.', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='ldapsyncjob',
            old_name='ldap_base_dn',
            new_name='base_ou',
        ),
        migrations.RenameField(
            model_name='ldapsyncjob',
            old_name='ldap_search_filter',
            new_name='logging_output',
        ),
        migrations.RemoveField(
            model_name='ldapsyncjob',
            name='removal_action',
        ),
        migrations.RemoveField(
            model_name='ldapsyncjob',
            name='removal_function',
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='create',
            field=models.BooleanField(default=True, help_text=b'If True then new models will '),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='delete_action',
            field=models.CharField(choices=[(b'DELETE', b'DELETE'), (b'FUNCTION', b'Function')], default=b'DELETE', max_length=50),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='delete_function',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='django_key_attribute',
            field=models.CharField(default='stuff', help_text=b'The name of a unique attribute on the Django model that will be used for syncing.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='ldap_key_attribute',
            field=models.CharField(default='stuff', help_text=b'The name of a unique attribute in the LDAP data that will be used for syncing.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='logging_level',
            field=models.CharField(choices=[(b'DEBUG', b'DEBUG'), (b'INFO', b'INFO'), (b'WARNING', b'WARNING'), (b'ERROR', b'ERROR'), (b'CRITICAL', b'CRITICAL')], default=b'INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='search_filter',
            field=models.TextField(default='stuff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='search_scope',
            field=models.CharField(choices=[(b'BASE', b'ldap3.BASE'), (b'LEVEL', b'ldap3.LEVEL'), (b'SUBTREE', b'ldap3.SUBTREE')], default=b'SUBTREE', max_length=100),
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='update',
            field=models.BooleanField(default=True, help_text=b'U'),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'jolly.casual.sole', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ldapsyncdjangoquerysetfilter',
            name='sync_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='ldap3_sync.LDAPSyncJob'),
        ),
        migrations.AddField(
            model_name='ldapsyncattributemap',
            name='sync_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ldap3_sync.LDAPSyncJob'),
        ),
    ]
