# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0005_auto_20170215_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPSyncJobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RenameField(
            model_name='ldapsyncjob',
            old_name='create',
            new_name='do_create',
        ),
        migrations.RenameField(
            model_name='ldapsyncjob',
            old_name='delete',
            new_name='do_delete',
        ),
        migrations.RenameField(
            model_name='ldapsyncjob',
            old_name='update',
            new_name='do_update',
        ),
        migrations.RemoveField(
            model_name='ldapsyncjob',
            name='logging_output',
        ),
        migrations.AddField(
            model_name='ldapsyncjob',
            name='synchronizer_class',
            field=models.CharField(default=b'ldap3_sync.utils.PETLSynchronizer', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'deeply.simple.tomcat', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='ldapsyncjoblog',
            name='sync_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ldap3_sync.LDAPSyncJob'),
        ),
    ]
