# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0006_auto_20170216_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapsyncjoblog',
            options={'ordering': ['started_at']},
        ),
        migrations.RemoveField(
            model_name='ldapsyncjoblog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ldapsyncjoblog',
            name='ended_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 11, 18, 32, 202000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsyncjoblog',
            name='started_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 17, 11, 18, 40, 339000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsyncjoblog',
            name='successful',
            field=models.BooleanField(default=True, help_text=b'Simple boolean indicator as to wether this Synchonization job was successful.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'firmly.tops.fawn', max_length=255, unique=True),
        ),
    ]
