# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0007_auto_20170217_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default=b'partly.fit.grouse', max_length=255, unique=True),
        ),
    ]
