# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldap3_sync', '0008_auto_20170217_1354'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ldapsyncrecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ldapsyncrecord',
            name='content_type',
        ),
        migrations.AlterModelOptions(
            name='ldapconnection',
            options={'verbose_name': 'ldap3.Connection', 'verbose_name_plural': 'ldap3.Connections'},
        ),
        migrations.AlterModelOptions(
            name='ldappool',
            options={'verbose_name': 'ldap3.ServerPool', 'verbose_name_plural': 'ldap3.ServerPools'},
        ),
        migrations.AlterModelOptions(
            name='ldapreferralhost',
            options={'verbose_name': 'ldap3.ReferralHost', 'verbose_name_plural': 'ldap3.ReferralHosts'},
        ),
        migrations.AlterModelOptions(
            name='ldapserver',
            options={'verbose_name': 'ldap3.Server', 'verbose_name_plural': 'ldap3.Servers'},
        ),
        migrations.AlterModelOptions(
            name='ldapsyncattributemap',
            options={'verbose_name': 'Synchronizer Attribute Map', 'verbose_name_plural': 'Synchronizer Attribute Maps'},
        ),
        migrations.AlterModelOptions(
            name='ldapsyncdjangoquerysetfilter',
            options={'verbose_name': 'Django Queryset Filters'},
        ),
        migrations.AlterModelOptions(
            name='ldapsyncjob',
            options={'verbose_name': 'Synchronizer Job', 'verbose_name_plural': 'Synchronizer Jobs'},
        ),
        migrations.AlterModelOptions(
            name='ldapsyncjoblog',
            options={'ordering': ['started_at'], 'verbose_name': 'Synchronizer Log', 'verbose_name_plural': 'Synchronizer Logs'},
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='authentication',
            field=models.CharField(blank=True, choices=[('ANONYMOUS', 'ldap3.ANONYMOUS'), ('SIMPLE', 'ldap3.SIMPLE'), ('SASL', 'ldap3.SASL'), ('NTLM', 'ldap3.NTLM')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='auto_bind',
            field=models.CharField(choices=[('NONE', 'ldap3.AUTO_BIND_NONE'), ('NO_TLS', 'ldap3.AUTO_BIND_NO_TLS'), ('TLS_AFTER_BIND', 'ldap3.AUTO_BIND_TLS_AFTER_BIND'), ('TLS_BEFORE_BIND', 'ldap3.AUTO_BIND_TLS_BEFORE_BIND')], default='NONE', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='client_strategy',
            field=models.CharField(choices=[('SYNC', 'ldap3.SYNC'), ('RESTARTABLE', 'ldap3.RESTARTABLE')], default='SYNC', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='password',
            field=models.CharField(blank=True, help_text='Password for the bind user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='sasl_credentials',
            field=models.CharField(blank=True, help_text='Path to an object to use as the SASL Credential.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='sasl_mechanism',
            field=models.CharField(blank=True, choices=[('EXTERNAL', 'ldap3.EXTERNAL'), ('DIGEST-MD5', 'ldap3.DIGEST_MD5'), ('GSSAPI', 'ldap3.KERBEROS'), ('GSSAPI', 'ldap3.GSSAPI')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ldapconnection',
            name='user',
            field=models.CharField(blank=True, help_text='Bind username for the LDAP server. Format is server dependent but is usually the distinguished name of the user.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldappool',
            name='pool_strategy',
            field=models.CharField(choices=[('FIRST', 'ldap3.FIRST'), ('ROUND_ROBIN', 'ldap3.ROUND_ROBIN'), ('RANDOM', 'ldap3.RANDOM')], default='ROUND_ROBIN', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='get_info',
            field=models.CharField(choices=[('NO_INFO', 'ldap3.NONE'), ('DSA', 'ldap3.DSA'), ('SCHEMA', 'ldap3.SCHEMA'), ('ALL', 'ldap3.ALL'), ('EDIR_8_8_8', 'ldap3.OFFLINE_EDIR_8_8_8'), ('AD_2012_R2', 'ldap3.OFFLINE_AD_2012_R2'), ('SLAPD_2_4', 'ldap3.OFFLINE_SLAPD_2_4'), ('DS389_1_3_3', 'ldap3.OFFLINE_DS389_1_3_3')], default='SCHEMA', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='mode',
            field=models.CharField(choices=[('IP_SYSTEM_DEFAULT', 'ldap3.IP_SYSTEM_DEFAULT'), ('IP_V4_ONLY', 'ldap3.IP_V4_ONLY'), ('IP_V6_ONLY', 'ldap3.IP_V6_ONLY'), ('IP_V4_PREFERRED', 'ldap3.IP_V4_PREFERRED'), ('IP_V6_PREFERRED', 'ldap3.IP_V6_PREFERRED')], default='IP_SYSTEM_DEFAULT', max_length=128),
        ),
        migrations.AlterField(
            model_name='ldapserver',
            name='tls',
            field=models.CharField(blank=True, help_text='Path to a python object which contains TLS certificate information. LEAVE THIS BLANK.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsyncattributemap',
            name='ldap_attribute_name',
            field=models.CharField(help_text='LDAP Attribute Name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncattributemap',
            name='model_attribute_name',
            field=models.CharField(help_text='Django Attribute Name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncdjangoquerysetfilter',
            name='predicate',
            field=models.CharField(help_text='Filter predicate.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncdjangoquerysetfilter',
            name='value',
            field=models.CharField(help_text='Value to filter against.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='delete_action',
            field=models.CharField(choices=[('DELETE', 'DELETE'), ('FUNCTION', 'Function')], default='DELETE', max_length=50),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='django_key_attribute',
            field=models.CharField(help_text='The name of a unique attribute on the Django model that will be used for syncing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='do_create',
            field=models.BooleanField(default=True, help_text='If True then new models will '),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='do_update',
            field=models.BooleanField(default=True, help_text='U'),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='ldap_key_attribute',
            field=models.CharField(help_text='The name of a unique attribute in the LDAP data that will be used for syncing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='logging_level',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='name',
            field=models.CharField(default='subtly.suited.fawn', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='search_scope',
            field=models.CharField(choices=[('BASE', 'ldap3.BASE'), ('LEVEL', 'ldap3.LEVEL'), ('SUBTREE', 'ldap3.SUBTREE')], default='SUBTREE', max_length=100),
        ),
        migrations.AlterField(
            model_name='ldapsyncjob',
            name='synchronizer_class',
            field=models.CharField(default='ldap3_sync.utils.PETLSynchronizer', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsyncjoblog',
            name='successful',
            field=models.BooleanField(help_text='Simple boolean indicator as to wether this Synchonization job was successful.'),
        ),
        migrations.DeleteModel(
            name='LDAPSyncRecord',
        ),
    ]
